# Generated by Django 3.2.7 on 2021-09-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='BlogApp/default.png', upload_to='BlogApp'),
        ),
    ]
