# Generated by Django 3.2.7 on 2021-09-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoriaPost', 'verbose_name_plural': 'categoriasPosts'},
        ),
    ]
