# Generated by Django 3.2.7 on 2021-09-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0002_auto_20210928_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'categoriaProducto', 'verbose_name_plural': 'categoriasProductos'},
        ),
    ]
